// useGetHotelsQuery is generated by `npm run codegen` from graphql/operations/hotels.graphql
// If this import fails, run: cd client/web && npm run codegen
import { useGetHotelsQuery } from "@modules/graphql/generated";
import { HotelCard } from "./HotelCard";

interface Props {
  onSelectHotel: (id: string, name: string) => void;
}

export function HotelList({ onSelectHotel }: Props) {
  const { data, loading, error } = useGetHotelsQuery();

  if (loading) return <p className="text-gray-500">Loading hotels…</p>;
  if (error) return <p className="text-red-600">Error: {error.message}</p>;
  if (!data?.hotels.length) return <p className="text-gray-500">No hotels found.</p>;

  return (
    <div className="flex flex-col gap-3">
      {data.hotels.map((hotel) => (
        <HotelCard key={hotel.id} hotel={hotel} onSelect={onSelectHotel} />
      ))}
    </div>
  );
}